name: "MiNiFi-CPP CI"
on: [push, pull_request, workflow_dispatch]
env:
  DOCKER_CMAKE_FLAGS: -DDOCKER_VERIFY_THREAD=3 -DUSE_SHARED_LIBS= -DSTRICT_GSL_CHECKS=AUDIT -DCI_BUILD=ON -DDISABLE_JEMALLOC=ON -DENABLE_AWS=ON -DENABLE_LIBRDKAFKA=ON -DENABLE_MQTT=ON -DENABLE_AZURE=ON -DENABLE_SQL=ON \
    -DENABLE_SPLUNK=ON -DENABLE_GCP=ON -DENABLE_OPC=ON -DENABLE_PYTHON_SCRIPTING=ON -DENABLE_LUA_SCRIPTING=ON -DENABLE_KUBERNETES=ON -DENABLE_TEST_PROCESSORS=ON -DENABLE_PROMETHEUS=ON \
    -DENABLE_ELASTICSEARCH=OFF -DDOCKER_BUILD_ONLY=ON
  SCCACHE_GHA_ENABLE: true
  CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/.ccache
jobs:
  macos_xcode:
    name: "macos-xcode"
    runs-on: macos-13
    timeout-minutes: 180
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: cache restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: macos-xcode-ccache-${{github.ref}}-${{github.sha}}
          restore-keys: |
            macos-xcode-ccache-${{github.ref}}-
            macos-xcode-ccache-refs/heads/main-
      - id: install_python_for_bootstrap
        run: |
          brew install --overwrite python
      - id: setup_env
        name: setup environment
        run: |
          echo "PATH=/usr/lib/ccache:/usr/local/opt/ccache/bin:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV
          echo -e "127.0.0.1\t$HOSTNAME" | sudo tee -a /etc/hosts > /dev/null
      - name: build
        run: |
          export PATH="/usr/local/opt/flex/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/flex/lib"
          export CPPFLAGS="-I/usr/local/opt/flex/include"
          cd bootstrap && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && python main.py --noninteractive --compiler_override="-DCMAKE_C_FLAGS=${CPPFLAGS} ${CFLAGS} -DCMAKE_CXX_FLAGS=${CPPFLAGS} ${CXXFLAGS}" --override="-DENABLE_PYTHON_SCRIPTING=ON -DENABLE_LUA_SCRIPTING=ON -DENABLE_SQL=ON -DUSE_REAL_ODBC_TEST_DRIVER=ON -DENABLE_AZURE=ON -DENABLE_GCP=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_RULE_MESSAGES=OFF -DSTRICT_GSL_CHECKS=AUDIT -DMINIFI_FAIL_ON_WARNINGS=ON"
      - name: cache save
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ${{ env.CCACHE_DIR }}
          key: macos-xcode-ccache-${{github.ref}}-${{github.sha}}
      - name: test
        id: test
        run: |
          # Set core file size limit to unlimited
          ulimit -c unlimited
          cd build && ctest -j4 --output-on-failure --timeout 300
      - name: linter
        run: cd build && ninja linter
      - name: check-cores
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
        run: |
          if [ "$(ls -A /cores)" ]; then echo "CORES_EXIST=true" >> $GITHUB_ENV; fi
      - uses: actions/upload-artifact@v3.1.2
        if: ${{ failure() && env.CORES_EXIST == 'true' }}
        with:
          name: macos-coredumps
          path: /cores
      - uses: actions/upload-artifact@v3.1.2
        if: ${{ failure() && env.CORES_EXIST == 'true' }}
        with:
          name: macos-binaries
          path: build/bin
  windows_VS2022:
    name: "windows-2022"
    runs-on: windows-2022
    timeout-minutes: 240
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - id: checkout
        uses: actions/checkout@v3
      - name: sccache cache restore
        uses: actions/cache/restore@v3
        with:
          path: ~/AppData/Local/Mozilla/sccache/cache
          key: ${{ runner.os }}-2022-sccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-2022-sccache-${{ github.ref }}
            ${{ runner.os }}-2022-sccache-refs/heads/main
            ${{ runner.os }}-2022-sccache
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Set up Python
        run: choco -y install python & refreshenv
        shell: cmd
      - name: Set up Lua
        uses: xpol/setup-lua@v0.3
      - id: install-sqliteodbc-driver
        run: |
          Invoke-WebRequest -Uri "http://www.ch-werner.de/sqliteodbc/sqliteodbc_w64.exe" -OutFile "sqliteodbc_w64.exe"
          if ((Get-FileHash 'sqliteodbc_w64.exe').Hash -ne "a4804e4f54f42c721df1323c5fcac101a8c7a577e7f20979227324ceab572d51") {Write "Hash mismatch"; Exit 1}
          Start-Process -FilePath ".\sqliteodbc_w64.exe" -ArgumentList "/S" -Wait
        shell: powershell
      - name: Install NASM
        run: |
          choco -y install NASM
        shell: cmd
      - name: Add NASM to path
        run: '[Environment]::SetEnvironmentVariable("PATH", [Environment]::GetEnvironmentVariable("PATH", [EnvironmentVariableTarget]::Machine) + ";C:\MyPath", [EnvironmentVariableTarget]::Machine);'
        shell: powershell
      - name: build
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install -r requirements.txt
          python main.py --noninteractive --compiler_override="-DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache" --override="-DCMAKE_BUILD_TYPE=Release -DCI_BUILD=ON -DMINIFI_FAIL_ON_WARNINGS=ON -DENABLE_AWS=ON -DENABLE_AZURE=ON -DENABLE_BUSTACHE=ON -DENABLE_COAP=ON -DENABLE_ENCRYPT_CONFIG=ON -DENABLE_PDH=ON -DENABLE_SPLUNK=ON -DENABLE_MQTT=ON -DENABLE_OPENCV=ON -DENABLE_OPENWSMAN=ON -DENABLE_OPS=ON -DENABLE_PCAP=OFF -DENABLE_SENSORS=ON -DENABLE_SFTP=ON -DENABLE_SQL=ON -DENABLE_SYSTEMD=ON -DENABLE_USB_CAMERA=OFF -DENABLE_PYTHON_SCRIPTING=OFF -DENABLE_LUA_SCRIPTING=OFF -DENABLE_KUBERNETES=ON -DENABLE_GCP=ON -DENABLE_PROMETHEUS=ON -DENABLE_ELASTICSEARCH=ON"
        shell: cmd
        working-directory: bootstrap
      - name: nasm version
        run: nasm.exe -v
        if: always()
        shell: cmd
        working-directory: c:\Strawberry\c\bin
      - name: sccache cache save
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/AppData/Local/Mozilla/sccache/cache
          key: ${{ runner.os }}-2022-sccache-${{ github.ref }}-${{ github.sha }}
      - name: test
        run: ctest --timeout 300 --parallel %NUMBER_OF_PROCESSORS% -C Release --output-on-failure
        shell: cmd
        working-directory: ./build
      - name: linter
        run: cmake --build . --target linter --config Release -j 8
        shell: cmd
        working-directory: ./build
