name: "MiNiFi-CPP memcheck"
on: [push, pull_request, workflow_dispatch]
env:
  CMAKE_FLAGS: >-
    -DCMAKE_BUILD_TYPE=Debug
    -DCI_BUILD=OFF
    -DCUSTOM_MALLOC=OFF
    -DDOCKER_BUILD_ONLY=OFF
    -DDOCKER_PUSH=OFF
    -DDOCKER_SKIP_TESTS=ON
    -DENABLE_ALL=OFF
    -DENABLE_AWS=OFF
    -DENABLE_AZURE=OFF
    -DENABLE_BUSTACHE=ON
    -DENABLE_BZIP2=ON
    -DENABLE_CIVET=ON
    -DENABLE_CONTROLLER=ON
    -DENABLE_ELASTICSEARCH=OFF
    -DENABLE_ENCRYPT_CONFIG=ON
    -DENABLE_EXPRESSION_LANGUAGE=ON
    -DENABLE_GCP=OFF
    -DENABLE_KUBERNETES=OFF
    -DENABLE_LIBARCHIVE=ON
    -DENABLE_LIBRDKAFKA=OFF
    -DENABLE_LUA_SCRIPTING=OFF
    -DENABLE_LZMA=ON
    -DENABLE_MQTT=OFF
    -DENABLE_OPC=OFF
    -DENABLE_OPENCV=OFF
    -DENABLE_OPS=ON
    -DENABLE_PROCFS=OFF
    -DENABLE_PROMETHEUS=ON
    -DENABLE_PYTHON_SCRIPTING=OFF
    -DENABLE_ROCKSDB=ON
    -DENABLE_SFTP=ON
    -DENABLE_SPLUNK=OFF
    -DENABLE_SQL=OFF
    -DENABLE_SYSTEMD=ON
    -DENABLE_TEST_PROCESSORS=OFF
    -DFORCE_COLORED_OUTPUT=ON
    -DMINIFI_FAIL_ON_WARNINGS=ON
    -DPORTABLE=ON
    -DSKIP_TESTS=OFF
    -DMINIFI_USE_REAL_ODBC_TEST_DRIVER=OFF
    -DUSE_SHARED_LIBS=ON
  SCCACHE_GHA_ENABLE: true
  CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/.ccache
jobs:
  ubuntu_24_04:
    name: "ubuntu-24.04"
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - name: cache restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: memcheck-ccache-${{github.ref}}-${{github.sha}}
          restore-keys: |
            memcheck-ccache-${{github.ref}}-
            memcheck-ccache-refs/heads/main-
      - id: install_deps
        run: |
          sudo apt update
          sudo apt install -y ccache libfl-dev python3 python3-venv valgrind
          echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
          echo -e "127.0.0.1\t$HOSTNAME" | sudo tee -a /etc/hosts > /dev/null
      - name: build
        run: |
          python3 -m venv venv && source venv/bin/activate \
            && pip install -r requirements.txt \
            && python main.py --noninteractive --minifi-options="${CMAKE_FLAGS}"
        working-directory: bootstrap
      - name: cache save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ env.CCACHE_DIR }}
          key: memcheck-ccache-${{github.ref}}-${{github.sha}}
      - name: test
        id: test
        run: |
          # Set core file size limit to unlimited
          ulimit -c unlimited
          ctest -j$(nproc) -L memchecked -T memcheck
        working-directory: build