name: "MiNiFi-CPP Verify Package"
on: [workflow_dispatch]
env:
  DOCKER_CMAKE_FLAGS: -DDOCKER_VERIFY_THREAD=3 -DUSE_SHARED_LIBS= -DSTRICT_GSL_CHECKS=AUDIT -DCI_BUILD=ON -DENABLE_AWS=ON -DENABLE_KAFKA=ON -DENABLE_MQTT=ON -DENABLE_AZURE=ON -DENABLE_SQL=ON \
    -DENABLE_SPLUNK=ON -DENABLE_GCP=ON -DENABLE_OPC=ON -DENABLE_PYTHON_SCRIPTING=ON -DENABLE_LUA_SCRIPTING=ON -DENABLE_KUBERNETES=ON -DENABLE_TEST_PROCESSORS=ON -DENABLE_PROMETHEUS=ON \
    -DENABLE_ELASTICSEARCH=OFF -DENABLE_GRAFANA_LOKI=ON -DENABLE_COUCHBASE=ON -DDOCKER_BUILD_ONLY=ON
  CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/.ccache
jobs:
  docker-tests:
    name: "${{ matrix.platform.name }}"
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { name: "Rocky Linux 8",
            id: "rocky8",
            build_cmd: "make rocky8_from_rocky_package",
            verify_cmd: "make docker-verify-rocky8" },
          { name: "Rocky Linux 9",
            id: "rocky9",
            build_cmd: "make rocky9_from_rocky_package",
            verify_cmd: "make docker-verify-rocky9" },
          { name: "Ubuntu 22.04",
            id: "ubuntu_jammy",
            build_cmd: "make jammy_from_rocky_package",
            verify_cmd: "make docker-verify-jammy" },
          { name: "Ubuntu 24.04",
            id: "ubuntu_noble",
            build_cmd: "make noble_from_rocky_package",
            verify_cmd: "make docker-verify-noble" },
          { name: "Debian 11",
            id: "debian_bullseye",
            build_cmd: "make bullseye_from_rocky_package",
            verify_cmd: "make docker-verify-bullseye" },
          { name: "Debian 12",
            id: "debian_bookworm",
            build_cmd: "make bookworm_from_rocky_package",
            verify_cmd: "make docker-verify-bookworm" },
        ]

    steps:
      - name: Get Workflow Database ID
        id: get-workflow-id
        run: |
          # Use the current branch name dynamically
          CURRENT_BRANCH=${{ github.ref_name }}
          echo "Current branch: $CURRENT_BRANCH"
          
          WORKFLOW_ID=$(gh run list --repo apache/nifi-minifi-cpp --branch main --limit 1 --json workflowDatabaseId --status success | jq -r '.[0].workflowDatabaseId')
          echo "Workflow ID: $WORKFLOW_ID"
          echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_ENV
      - id: checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: minifi-tar
          path: build
          run-id: $WORKFLOW_ID
      - id: install_deps
        run: |
          sudo apt update
          sudo apt install -y python3-virtualenv
      - run: cd build && cmake ${DOCKER_CMAKE_FLAGS} .. \
          && ${{ matrix.platform.build_cmd }} && ${{ matrix.platform.verify_cmd }}
      - name: Test Reporter
        if: always()
        uses: phoenix-actions/test-reporting@v15
        with:
          name: "${{ matrix.platform.name }}"
          path: build/behavex_output/behave/*.xml
          reporter: java-junit
          output-to: 'step-summary'
          list-tests: 'failed'
          list-suites: 'failed'
      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.id }}_behavex_output
          path: build/behavex_output
